[workspace]
resolver = "2"
members = [
    "app",
    "core",
    "macros",
    "background",
    "extensions/chrome",
]
default-members = ["app"]


[workspace.package]
version = "0.1.0"
authors = ["ASPECTRON Inc."]
license = "MIT/Apache-2.0"
edition = "2021"


[workspace.dependencies]
kaspa-ng = { version = "0.1.0", path = "app/" }
kaspa-ng-core = { version = "0.1.0", path = "core/" }
kaspa-ng-macros = { version = "0.1.0", path = "macros/" }
kaspa-ng-background = { version = "0.1.0", path = "background/" }

# kaspa-wallet-core = { git = "https://github.com/kaspanet/rusty-kaspa.git", branch = "master" }
# kaspa-wrpc-client = { git = "https://github.com/kaspanet/rusty-kaspa.git", branch = "master" }
# kaspad = { git = "https://github.com/kaspanet/rusty-kaspa.git", branch = "master" }
kaspa-consensus-core = { path = "../rusty-kaspa/consensus/core" }
kaspa-wallet-core = { path = "../rusty-kaspa/wallet/core", features=["no-unsafe-eval"] }
kaspa-rpc-core = { path = "../rusty-kaspa/rpc/core" }
kaspa-wrpc-client = { path = "../rusty-kaspa/rpc/wrpc/client", features=["no-unsafe-eval"] }
kaspa-utils = { path = "../rusty-kaspa/utils" }
kaspa-bip32 = { path = "../rusty-kaspa/wallet/bip32" }

# workflow-core = "0.6.0"
# workflow-log = "0.6.0"
# workflow-dom = "0.6.0"
workflow-log = { path = "../workflow-rs/log" }
workflow-core = { path = "../workflow-rs/core", features = ["no-unsafe-eval"] }
workflow-dom = { path = "../workflow-rs/dom" }
workflow-store = { path = "../workflow-rs/store" }


cfg-if = "1.0.0"
log = "0.4"
serde = { version = "1", features = ["derive"] }
thiserror = "1.0.47"
derivative = "2.2.0"
downcast = "0.11.0"
downcast-rs = "1.2.0"
separator = "0.4.1"
futures = { version = "0.3" }
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
zeroize = { version = "1", default-features = false, features = ["alloc"] }
async-trait = "0.1.73"
slug = "0.1.4"
qrcode = "0.12.0"
js-sys = "0.3.64"
wasm-bindgen = "0.2.87"
rand = "0.8"


# egui = "0.22.0"
# egui_extras = { version = "0.22.0", features = ["svg"] }
# eframe = { version = "0.22.0", default-features = false, features = [
#     "accesskit",     # Make egui comptaible with screen readers. NOTE: adds a lot of dependencies.
#     "default_fonts", # Embed the default egui fonts.
#     "glow",          # Use the glow rendering backend. Alternative: "wgpu".
#     "persistence",   # Enable restoring app state when restarting the app.
# ] }
# egui-phosphor = { version = "0.2.0", features = ["thin","light","regular","bold"] }
# egui-notify = "0.9.0"
# egui-toast = "0.9.0"

egui = { path = "../egui/crates/egui" }
egui_extras = { path = "../egui/crates/egui_extras", features = ["svg"] }
eframe = { path = "../egui/crates/eframe", default-features = false, features = [
    "accesskit",     # Make egui comptaible with screen readers. NOTE: adds a lot of dependencies.
    "default_fonts", # Embed the default egui fonts.
    "glow",          # Use the glow rendering backend. Alternative: "wgpu".
    "persistence",   # Enable restoring app state when restarting the app.
] }
egui-phosphor = { path = "../egui-phosphor", features = ["thin","light","regular","bold"] }
egui-notify = { path = "../egui-notify" }
# egui-toast = { path = "../egui-toast" }

web-sys = { version = "0.3.64", features = [
    # 'console',
    # 'Document',
    # 'Element',
    # 'HtmlElement',
    'Window',
] }

# native:
kaspad = { path = "../rusty-kaspa/kaspad" }
kaspa-rpc-service = { path = "../rusty-kaspa/rpc/service" }
kaspa-wrpc-server = { path = "../rusty-kaspa/rpc/wrpc/server" }
kaspa-core = { path = "../rusty-kaspa/core" }
tokio = { version = "1", features = ["sync", "rt-multi-thread"] }
ctrlc = { version = "3.2", features = ["termination"] }
env_logger = "0.10"
num_cpus = "1.15.0"


# web:
wasm-bindgen-futures = "0.4"

[profile.release]
opt-level = 2 # fast and small wasm
