[package]
name = "kaspa-ng-background"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[features]
browser-extension = []
default = ["browser-extension"]

[dependencies]
kaspa-wallet-core.workspace = true
