[build]
target = "index.html"
# Build in release mode.
release = false
# The output dir for all final assets.
dist = "../../dist-chrome"

# DOCS:
# https://github.com/thedodd/trunk/blob/master/Trunk.toml
# https://trunkrs.dev/assets/#rust
