[build]
target = "tunk.html"
# Build in release mode.
release = false
# The output dir for all final assets.
dist = "../../dist-chrome"
# Whether to inject scripts (and module preloads) into the finalized output.
inject_scripts = false

# DOCS:
# https://github.com/thedodd/trunk/blob/master/Trunk.toml
# https://trunkrs.dev/assets/#rust

# [[hooks]]
# stage = "post_build"
# command = "wasm-pack" # build --target web --out-name wasm --out-dir ./pkg"
# command_arguments = ["build", "--target", "web", "--out-name", "background", "--out-dir", "../../dist-chrome", "./extensions/chrome/"]
